provider:
  default:
    language: 2.6

environment:
  RACK_ENV: production

engines:
  puma: bundle exec puma -p 3000 -e production -w $(nproc)
  falcon: bundle exec falcon serve --bind http://0.0.0.0:3000
  iodine: bundle exec iodine -bind 0.0.0.0 -port 3000
