framework:
  website: rubyonrails.org
  version: 6.0

files:

  default:

    - app
    - config
    - config.ru
    - Rakefile

  puma:

    Gemfile: puma/Gemfile

  falcon:

    Gemfile: falcon/Gemfile

  iodine:

    Gemfile: iodine/Gemfile
  
default_runtime: puma